// ─── Schwangerschafts-Entwicklungsinhalte ────────────────────────────────────
// 11 Blöcke á 2-4 Wochen, SSW 4–40
// Quellen: WHO, DGGG, Pschyrembel, BZgA "Schwangerschaft und Geburt"

export interface PregnancyBlock {
  sswFrom: number;
  sswTo: number;
  ageLabel: string;           // "SSW 4–5"
  trimester: 1 | 2 | 3;
  babySize: string;           // Vergleichsgröße
  babyWeightApprox: string;   // "ca. 1 g"
  babyDev: string[];          // Was passiert beim Baby
  bodyChanges: string[];      // Was passiert im Körper der Mutter
  isNormal: string[];         // Das ist normal (beruhigend)
  watchOut: string[];         // Warnzeichen
  todos: string[];            // Action Layer
  tips: string[];             // Praktische Tipps
  forParents: string;         // Emotionaler Layer
  nextWeekPreview: string;    // Was kommt als nächstes
}

export const PREGNANCY_BLOCKS: PregnancyBlock[] = [
  {
    sswFrom: 4,
    sswTo: 5,
    ageLabel: "SSW 4–5",
    trimester: 1,
    babySize: "Mohnkorn",
    babyWeightApprox: "< 1 g",
    babyDev: [
      "Die Einnistung ist abgeschlossen — dein Baby ist jetzt offiziell Teil von dir",
      "Herz, Gehirn, Rückenmark und Verdauungstrakt beginnen sich anzulegen",
      "Der Herzschlag setzt ein — noch winzig, aber da",
      "Der Embryo ist ca. 1–3 mm groß",
    ],
    bodyChanges: [
      "Der Schwangerschaftstest zeigt positiv — hCG steigt rasant",
      "Brüste können sich gespannt, wärmer oder empfindlicher anfühlen",
      "Leichte Übelkeit kann beginnen — besonders morgens",
      "Müdigkeit ist jetzt sehr häufig und völlig normal",
      "Leichtes Ziehen im Unterleib durch Einpflanzung",
    ],
    isNormal: [
      "Leichte Schmierblutung (Einnistungsblutung) für 1–2 Tage",
      "Stimmungsschwankungen durch den Hormonsturm",
      "Häufiger Harndrang",
      "Erhöhte Körpertemperatur",
      "Verstärkte Geruchsempfindlichkeit",
    ],
    watchOut: [
      "Starke Blutungen — sofort Arzt kontaktieren",
      "Starke einseitige Unterleibsschmerzen (mögliche Eileiterschwangerschaft)",
      "Fieber über 38,5°C",
    ],
    todos: [
      "Gynäkologen-Termin für den ersten Ultraschall vereinbaren (ca. SSW 8–10)",
      "Frühzeitig Hebamme suchen — viele sind schnell ausgebucht",
      "Folsäure täglich einnehmen (400–800 µg) — jetzt besonders wichtig",
      "Alkohol, Rauchen und Rohkostprodukte meiden",
      "Medikamente nur nach Rücksprache mit dem Arzt",
    ],
    tips: [
      "Ingwertee oder Salzcracker helfen bei Übelkeit",
      "Kleine, häufige Mahlzeiten statt drei großer",
      "Ruhepausen einplanen — Müdigkeit ist real, nicht Faulheit",
      "Lieber noch niemanden informieren bis SSW 12, wenn du noch nicht bereit bist",
    ],
    forParents: "Die ersten Wochen sind oft ein Wechselbad aus Freude, Angst und Erschöpfung. Du musst dir keine Sorgen machen, wenn sich die Schwangerschaft noch nicht real anfühlt — das ist ganz normal. Dein Körper arbeitet gerade auf Hochtouren.",
    nextWeekPreview: "In SSW 6–7 ist der Herzschlag im Ultraschall oft erstmals sichtbar — ein unvergesslicher Moment.",
  },
  {
    sswFrom: 6,
    sswTo: 7,
    ageLabel: "SSW 6–7",
    trimester: 1,
    babySize: "Linse",
    babyWeightApprox: "ca. 1 g",
    babyDev: [
      "Der Herzschlag ist jetzt im Ultraschall sichtbar — ca. 100–120 Schläge/Min",
      "Arme und Beine beginnen als kleine Knospen zu wachsen",
      "Gehirn und Rückenmark entwickeln sich rasant",
      "Gesichtszüge beginnen sich anzulegen: Augen, Nase, Mund",
      "Der Embryo ist ca. 5–13 mm groß",
    ],
    bodyChanges: [
      "Übelkeit erreicht häufig den Höhepunkt — morgens, aber auch den ganzen Tag",
      "Brüste wachsen und schmerzen stärker",
      "Gebärmutter ist auf die Größe einer Orange gewachsen",
      "Häufiger Harndrang durch Druckveränderungen",
      "Speichelfluss kann zunehmen",
    ],
    isNormal: [
      "Morgendliche Übelkeit auch mittags und abends",
      "Wenig Appetit oder sehr spezifische Gelüste",
      "Leichter Schwindel beim schnellen Aufstehen",
      "Verstopfung durch Progesteron",
      "Brustwarzen können dunkler werden",
    ],
    watchOut: [
      "Starkes Erbrechen, das keine Flüssigkeit zulässt (Hyperemesis) — Arzt aufsuchen",
      "Blutungen stärker als eine Regelblutung",
      "Anhaltende starke einseitige Schmerzen",
    ],
    todos: [
      "Ersten Ultraschall-Termin wahrnehmen — Herzschlag bestätigen",
      "Mutterpass ausstellen lassen",
      "Folsäure weiter täglich einnehmen",
      "Mit dem Arbeitgeber über Schwangerschaft nachdenken (Mutterschutz-Info)",
    ],
    tips: [
      "Leerer Magen verschlimmert Übelkeit — Cracker neben dem Bett für morgens",
      "Kühle, frische Luft hilft vielen bei Übelkeit",
      "Eisernes einhalten von regelmäßigen Schlafzeiten reduziert Erschöpfung",
      "Starke Gerüche meiden, wenn sie Übelkeit auslösen",
    ],
    forParents: "Übelkeit in dieser Phase ist ein Zeichen, dass der Schwangerschaftshormon-Spiegel hoch ist — tatsächlich ein gutes Zeichen. Das macht es nicht leichter zu ertragen, aber vielleicht ein bisschen leichter zu akzeptieren.",
    nextWeekPreview: "In SSW 8–9 beginnt das Baby, sich zu bewegen — noch nicht spürbar, aber es macht schon Übungen.",
  },
  {
    sswFrom: 8,
    sswTo: 9,
    ageLabel: "SSW 8–9",
    trimester: 1,
    babySize: "Olive",
    babyWeightApprox: "ca. 2 g",
    babyDev: [
      "Alle wichtigen Organe sind angelegt — Herz, Lunge, Nieren, Gehirn",
      "Das Baby bewegt sich bereits — du spürst es noch nicht",
      "Finger und Zehen werden erkennbar",
      "Die Schwanzanlage verschwindet — aus dem Embryo wird ein Fötus",
      "Das Gehirn wächst täglich messbar",
    ],
    bodyChanges: [
      "Gebärmutter ist auf Faustgröße gewachsen",
      "Unterbauch kann sich leicht gewölbt anfühlen",
      "Übelkeit hält oft an",
      "Mehr Ausfluss ist normal — der Schleimpfropf bildet sich",
      "Kreislaufprobleme durch Blutvolumen-Zunahme (+40% bis Ende)",
    ],
    isNormal: [
      "Weißlich-gelblicher Ausfluss (Schleimpfropf bildet sich)",
      "Schwindel, besonders beim Aufstehen",
      "Verstärkte Müdigkeit",
      "Häufigere Träume, ungewöhnlich lebhaft",
      "Emotionale Empfindlichkeit",
    ],
    watchOut: [
      "Blutungen mit Schmerzen",
      "Fieber über 38°C",
      "Kein Herzschlag im Ultraschall — Arzt entscheidet über weiteres Vorgehen",
    ],
    todos: [
      "Blutuntersuchung: Blutbild, Blutgruppe, Röteln-Immunität, HIV beim ersten Termin",
      "Krankenversicherung über Schwangerschaft informieren",
      "Geburtsvorbereitungskurs vormerken (meist ab SSW 28)",
    ],
    tips: [
      "Sanfte Bewegung (Spazierengehen, Schwimmen) hilft gegen Erschöpfung",
      "Ausreichend Wasser trinken — mindestens 1,5–2 Liter täglich",
      "Omega-3-reiche Ernährung (Lachs, Leinsamen) ist jetzt wichtig für die Gehirnentwicklung",
    ],
    forParents: "Die ersten drei Monate gelten als die Zeit der größten Veränderungen — und gleichzeitig sieht und fühlt man oft noch wenig davon. Das kann frustrierend sein. Du trägst schon längst eine Schwangerschaft, auch wenn es sich nicht immer so anfühlt.",
    nextWeekPreview: "In SSW 10–12 beginnt das erste Trimester-Screening — wichtige Informationen über die Entwicklung.",
  },
  {
    sswFrom: 10,
    sswTo: 12,
    ageLabel: "SSW 10–12",
    trimester: 1,
    babySize: "Pflaume",
    babyWeightApprox: "ca. 14 g",
    babyDev: [
      "Alle Organe sind voll angelegt — jetzt geht es ums Wachsen und Reifen",
      "Fingerabdrücke entwickeln sich",
      "Das Baby schluckt Fruchtwasser und übt Atembewegungen",
      "Äußere Geschlechtsmerkmale beginnen sich zu zeigen",
      "Gehirn entwickelt sich besonders schnell",
    ],
    bodyChanges: [
      "Das Risiko einer Fehlgeburt sinkt nach SSW 12 deutlich",
      "Übelkeit lässt bei vielen nach SSW 12 nach",
      "Bauch wächst sichtbar — Zeit für Umstandskleidung",
      "Blutvolumen steigt weiter — Herz schlägt schneller",
      "Haut kann rosiger wirken durch erhöhte Durchblutung",
    ],
    isNormal: [
      "Bauchschmerzen durch wachsende Gebärmutter und Bänder",
      "Sodbrennen beginnt bei manchen",
      "Nasenbluten durch erhöhten Blutdruck in Schleimhäuten",
      "Leichte Wassereinlagerungen",
    ],
    watchOut: [
      "Ergebnis des Ersttrimester-Screenings mit Arzt besprechen",
      "Nackentransparenz-Messung wahrnehmen (SSW 11–14)",
      "Blutungen immer sofort melden",
    ],
    todos: [
      "Ersttrimester-Screening (Ultraschall + Blut, SSW 11–14) — Nackentransparenz",
      "Schwangerschaft bekannt geben, wenn ihr bereit seid",
      "Arbeitgeber rechtzeitig informieren",
      "Wohnsituation, Finanzen und Elternzeit zu planen beginnen",
    ],
    tips: [
      "Wenn Übelkeit nachlässt: ausgewogene, eisenreiche Ernährung beginnen",
      "Sanfte Bauchgymnastik oder Schwangerschaftsyoga sind jetzt gut geeignet",
      "Schlaf auf der Seite ist ab jetzt besser als auf dem Bauch",
    ],
    forParents: "Das Ende des ersten Trimesters ist für viele eine emotionale Erleichterung. Das Risiko einer Fehlgeburt sinkt deutlich. Trotzdem ist es vollkommen normal, wenn die Sorgen nicht einfach verschwinden — Schwangerschaft bedeutet auch emotionale Arbeit.",
    nextWeekPreview: "Ab SSW 13 beginnt das 2. Trimester — für viele die angenehmste Phase, mit mehr Energie und spürbarem Bauch.",
  },
  {
    sswFrom: 13,
    sswTo: 16,
    ageLabel: "SSW 13–16",
    trimester: 2,
    babySize: "Avocado",
    babyWeightApprox: "ca. 100 g",
    babyDev: [
      "Das Baby macht koordinierte Bewegungen mit Armen und Beinen",
      "Mimik entwickelt sich — Stirnrunzeln, Gähnen ist möglich",
      "Haare und Augenbrauen wachsen",
      "Gehör entwickelt sich — das Baby reagiert auf laute Geräusche",
      "Nieren produzieren Urin, der als Fruchtwasser ausgeschieden wird",
    ],
    bodyChanges: [
      "Das 2. Trimester bringt bei vielen mehr Energie zurück",
      "Bauch wird deutlich sichtbar",
      "Libido kann sich verändern — in beide Richtungen",
      "Rückenschmerzen können beginnen durch veränderte Schwerpunktlage",
      "Zahnfleisch blutet leichter durch hormonelle Veränderungen",
    ],
    isNormal: [
      "Erste, ganz leichte Kindsbewegungen (wie Schmetterlinge) — besonders bei Mehrgebärenden",
      "Wachstumsschmerzen in den Bändern der Gebärmutter",
      "Kleine Pigmentveränderungen (Linea nigra am Bauch)",
      "Vergesslichkeit — das sogenannte 'Schwangerschaftshirn'",
    ],
    watchOut: [
      "Starke Rückenschmerzen mit Ausstrahlung — Arzt aufsuchen",
      "Blutungen jeder Art",
      "Plötzlich keine Bewegungen mehr (sobald man sie spürt)",
    ],
    todos: [
      "Großen Mutterpass-Ultraschall (SSW 18–22) vormerken",
      "Zahnärztin aufsuchen — Schwangerschaftsgingivitis vorbeugen",
      "Geburtsvorbereitungskurs buchen (früh buchen, viele sind ausgebucht)",
      "Eisenpräparate bei niedrigem Ferritin — Blutbild kontrollieren",
    ],
    tips: [
      "Seitenschläferkissen erleichtert den Schlaf auf der Seite",
      "Bauch eincremen gegen Dehnungsstreifen — ab jetzt täglich",
      "Regelmäßige Beckenbodenübungen beginnen — jetzt, nicht nach der Geburt",
      "Ausreichend Kalzium: täglich Milchprodukte oder Hülsenfrüchte",
    ],
    forParents: "Das zweite Trimester gilt als das 'goldene Trimester' — Übelkeit ist meist weg, der Bauch noch nicht zu groß. Genieße diese Phase bewusst. Es ist auch eine gute Zeit, als Paar über Erziehungsvorstellungen zu sprechen, bevor der Alltag beginnt.",
    nextWeekPreview: "In SSW 17–20 kommt das erste große Ultraschall-Screening — und viele spüren das Baby zum ersten Mal deutlich.",
  },
  {
    sswFrom: 17,
    sswTo: 20,
    ageLabel: "SSW 17–20",
    trimester: 2,
    babySize: "Mango",
    babyWeightApprox: "ca. 300 g",
    babyDev: [
      "Das Baby hört jetzt deutlich — deine Stimme ist vertraut",
      "Kindsbewegungen werden deutlicher und häufiger",
      "Geschlecht ist im Ultraschall erkennbar (wenn gewünscht)",
      "Gehirn bildet Millionen Nervenzellen täglich",
      "Das Baby schläft und wacht in regelmäßigen Zyklen",
    ],
    bodyChanges: [
      "Kindsbewegungen jetzt für die meisten deutlich spürbar (Quickening)",
      "Bauch wächst deutlich sichtbar",
      "Kreislauf arbeitet auf Hochtouren — Blutdruck kann sinken",
      "Manche bekommen erste Wassereinlagerungen an Füßen und Händen",
      "Gewichtszunahme: ca. 5–7 kg bis jetzt ist typisch",
    ],
    isNormal: [
      "Bewegungen mal mehr, mal weniger spürbar — das Muster stabilisiert sich erst später",
      "Nasenbluten durch erhöhten Blutfluss",
      "Wachstumsschmerzen im Becken und an den Seiten",
      "Schwitzen durch erhöhten Stoffwechsel",
    ],
    watchOut: [
      "Plötzlicher starker Kopfschmerz mit Sehstörungen (Präeklampsie-Zeichen)",
      "Keine Bewegungen mehr nach SSW 20 — sofort Arzt",
      "Druckgefühl im Becken früher als erwartet",
    ],
    todos: [
      "Großer Ultraschall (20. SSW-Screening) — Organe, Lage, Fruchtwasser",
      "Geburtsort entscheiden: Krankenhaus, Geburtshaus, Hausgeburt",
      "Klinikbeutel langsam zusammenstellen",
      "Babyraum und Erstausstattung planen",
    ],
    tips: [
      "Dem Baby vorlesen oder Musik vorspielen — es hört wirklich zu",
      "Bewegungsmuster kennenlernen — zu welcher Tageszeit ist es aktiv?",
      "Auf ausreichend Eisen achten: rotes Fleisch, Hülsenfrüchte, Kürbiskerne",
      "Schlaf auf der linken Seite verbessert die Durchblutung der Plazenta",
    ],
    forParents: "Die ersten spürbaren Bewegungen sind für viele der Moment, in dem die Schwangerschaft wirklich 'real' wird. Es ist auch normal, wenn man sich in dieser Phase intensiv Sorgen um die Gesundheit des Babys macht — das ist kein Zeichen von Angststörung, sondern von Liebe.",
    nextWeekPreview: "In SSW 21–24 stabilisiert sich das Bewegungsmuster — und das Baby beginnt, auf deine Stimme zu reagieren.",
  },
  {
    sswFrom: 21,
    sswTo: 24,
    ageLabel: "SSW 21–24",
    trimester: 2,
    babySize: "Mais",
    babyWeightApprox: "ca. 600 g",
    babyDev: [
      "Das Baby reagiert auf Geräusche und dreht sich dazu",
      "Lunge entwickelt sich — Surfactant (Lungenaushärter) wird gebildet",
      "Gehirn bildet Windungen und wird komplexer",
      "Greifreflex ist bereits vorhanden",
      "Überlebensfähigkeit beginnt ab SSW 24 (unter intensivmedizinischer Versorgung)",
    ],
    bodyChanges: [
      "Bauch wächst ca. 1 cm pro Woche",
      "Rückenschmerzen nehmen zu — Schwerpunkt verlagert sich weiter",
      "Sodbrennen durch zunehmenden Druck auf den Magen",
      "Schlafqualität kann sinken durch den Bauch",
      "Manche bekommen Schwangerschaftsstreifen",
    ],
    isNormal: [
      "Braxton-Hicks-Wehen beginnen (schmerzlose Trainingskon­traktionen)",
      "Stärkere Bewegungen, gelegentlich unter den Rippen",
      "Sodbrennen besonders nach dem Essen",
      "Vergesslichkeit und Konzentrationsschwäche",
    ],
    watchOut: [
      "Mehr als 5 Kontraktionen pro Stunde vor SSW 37 — sofort Kreißsaal",
      "Plötzliche starke Rückenschmerzen mit Fieber (Nierenentzündung)",
      "Schwellung von Händen und Gesicht (nicht nur Füße)",
    ],
    todos: [
      "Geburtsvorbereitungskurs wahrnehmen",
      "Krankenkasse: Anspruch auf Hebammenbetreuung klären",
      "Notfallnummern im Handy speichern (Kreißsaal, Hebamme)",
      "Klinikbeutel weiter packen",
    ],
    tips: [
      "Kleine Mahlzeiten gegen Sodbrennen — abends früh essen",
      "Seitenlage mit Kissen zwischen den Knien entlastet die Wirbelsäule",
      "Schwangerschaftsgymnastik oder Wassergymnastik — jetzt besonders gut",
      "Mit dem Partner üben: Massage, Atemübungen — ihr werdet es brauchen",
    ],
    forParents: "In dieser Phase merken viele, dass die Schwangerschaft ihr Leben bereits verändert — Schlaf, Spontaneität, der Körper. Das kann schön und gleichzeitig überwältigend sein. Beides darf nebeneinander existieren.",
    nextWeekPreview: "In SSW 25–28 wächst das Baby stark — und die Lunge reift weiter.",
  },
  {
    sswFrom: 25,
    sswTo: 28,
    ageLabel: "SSW 25–28",
    trimester: 3,
    babySize: "Aubergine",
    babyWeightApprox: "ca. 1.000 g",
    babyDev: [
      "Lunge reift weiter — Surfactantproduktion steigt",
      "Augen öffnen sich — das Baby blinzelt",
      "Gehörnerv ist voll entwickelt — das Baby erkennt Stimmen",
      "Fettdepots werden aufgebaut, Haut wird glatter",
      "Schlaf-Wach-Rhythmus wird regelmäßiger",
    ],
    bodyChanges: [
      "3. Trimester beginnt mit SSW 28 — Zielgerade",
      "Gewichtszunahme beschleunigt sich: ca. 500 g/Woche",
      "Kurzatmigkeit durch Druck auf die Lunge",
      "Hämorrhoiden und Krampfadern möglich durch erhöhten Druck",
      "Becken lockert sich hormonell — Symphysenschmerzen möglich",
    ],
    isNormal: [
      "Zunehmende Rücken- und Beckenschmerzen",
      "Braxton-Hicks-Wehen häufiger",
      "Schlafprobleme durch Bauch, Hitze und Gedankenkarussell",
      "Kolostrum (Vormilch) kann austreten",
    ],
    watchOut: [
      "Starke Kopfschmerzen + Sehstörungen + Gesichtsschwellung → Präeklampsie — Notruf",
      "Vorzeitige regelmäßige Wehen vor SSW 37",
      "Wasser verlieren (Blasensprung)",
      "Reduzierte Kindsbewegungen",
    ],
    todos: [
      "Glukosetoleranztest (Gestationsdiabetes-Screening, SSW 24–28) wahrnehmen",
      "Betriebsarzt / Mutterschutzgesetz mit Arbeitgeber besprechen",
      "Stillkissen, Wickelunterlage, Babyausstattung fertigstellen",
      "Geburtsplan beginnen: Wünsche für die Geburt formulieren",
    ],
    tips: [
      "Hochlegen der Beine gegen Wassereinlagerungen und Krampfadern",
      "Kompressionsstrümpfe bei langen Arbeitstagen",
      "Magnesium gegen Wadenkrämpfe — nach Rücksprache mit Arzt",
      "Stillvorbereitung: Informationen sammeln, Kurse besuchen",
    ],
    forParents: "Du hast jetzt mehr als die Hälfte geschafft — und das Baby ist schon eine echte Persönlichkeit. Es ist die Zeit, sich emotional auf die Geburt vorzubereiten: Welche Ängste hast du? Welche Hoffnungen? Darüber reden hilft mehr als verdrängen.",
    nextWeekPreview: "In SSW 29–32 nimmt das Baby stark an Gewicht zu — und Bewegungen werden intensiver und manchmal schmerzhafter.",
  },
  {
    sswFrom: 29,
    sswTo: 32,
    ageLabel: "SSW 29–32",
    trimester: 3,
    babySize: "Butternusskürbis",
    babyWeightApprox: "ca. 1.700 g",
    babyDev: [
      "Starke Gewichtszunahme — jetzt ca. 200 g pro Woche",
      "Gehirn wächst rasant — Windungen vertiefen sich",
      "Lunge fast ausgereift — Frühgeburten ab SSW 32 haben sehr gute Prognosen",
      "Knochen härten sich weiter (benötigt Kalzium!)",
      "Kindsbewegungen werden kräftiger und manchmal schmerzhafter",
    ],
    bodyChanges: [
      "Bauch wird schnell größer — Nabel kann heraustreten",
      "Atemnot durch Druck auf das Zwerchfell",
      "Häufiger Harndrang durch Druck auf die Blase",
      "Symphysenschmerzen (SPD) beim Gehen möglich",
      "Schlechte Schlafqualität — Schlafpositionen werden eingeschränkter",
    ],
    isNormal: [
      "Kräftige Tritte unter den Rippen",
      "Regelmäßige Braxton-Hicks",
      "Starkes Sodbrennen",
      "Vergesslichkeit und Konzentrationsprobleme",
      "Stimmungschwankungen und Geburtsangst",
    ],
    watchOut: [
      "Regelmäßige Wehen (alle 5–10 Min) vor SSW 37 → Kreißsaal",
      "Klares Fruchtwasser verlieren",
      "Starke Kopfschmerzen, Sehstörungen, Gesichtsschwellung",
      "Wenig oder keine Kindsbewegungen über mehrere Stunden",
    ],
    todos: [
      "Klinikbeutel fertig packen (für alle Fälle)",
      "Geburtsplan mit Hebamme oder Arzt besprechen",
      "Wochenbettplanung: wer hilft wie nach der Geburt?",
      "Elterngeld beantragen — Antrag liegt bei Standesamt oder online",
    ],
    tips: [
      "Schwimmen ist jetzt besonders wohltuend — nimmt den Druck",
      "Geburtsvorbereitungsübungen: Atmen, Entspannungstechniken üben",
      "Schlafen mit aufgekeiltem Oberkörper gegen Sodbrennen",
      "Kalziumreiche Ernährung für Knochen des Babys: Milch, Brokkoli, Sesam",
    ],
    forParents: "Geburtsangst ist in diesem Stadium sehr verbreitet — und vollkommen verständlich. Wenn du merkst, dass Angst überhandnimmt, sprich mit deiner Hebamme oder Ärztin. Es gibt konkrete Hilfen, und du musst das nicht alleine durchstehen.",
    nextWeekPreview: "In SSW 33–36 dreht sich das Baby idealerweise in die Geburtsposition — Kopf nach unten.",
  },
  {
    sswFrom: 33,
    sswTo: 36,
    ageLabel: "SSW 33–36",
    trimester: 3,
    babySize: "Honigmelone",
    babyWeightApprox: "ca. 2.500 g",
    babyDev: [
      "Das Baby dreht sich idealerweise in Schädellage (Kopf unten)",
      "Lunge ist fast vollständig ausgereift",
      "Fettgewebe wird weiter aufgebaut — das Baby 'rundet' sich",
      "Immunsystem reift — Antikörper werden über die Plazenta übertragen",
      "Schlafdauer: ca. 90–95% des Tages",
    ],
    bodyChanges: [
      "Bauch senkt sich wenn das Baby in Schädellage tritt",
      "Atemnot kann sich etwas verbessern wenn Baby tiefer rutscht",
      "Beckendruckgefühl und Druck auf die Blase werden stärker",
      "Erschöpfung nimmt zu — der Körper bereitet sich vor",
      "Kolostrum-Ausfluss häufiger",
    ],
    isNormal: [
      "Stärkerer Ausfluss, manchmal schleimig (Zeichnen des Schleimpfropfs)",
      "Stärkere Braxton-Hicks-Wehen",
      "Nestbautrieb — plötzlicher Drang, alles zu organisieren",
      "Schlaflosigkeit und Gedankenkarussel",
    ],
    watchOut: [
      "Regelmäßige Wehen alle 5–10 Min oder stärker",
      "Blasensprung (auch wenn kein Wehen folgen)",
      "Weniger Kindsbewegungen als gewohnt",
      "Baby liegt nach SSW 36 noch in Beckenendlage → mit Arzt besprechen (äußere Wendung möglich)",
    ],
    todos: [
      "Lage des Babys beim Ultraschall prüfen lassen",
      "Klinikbeutel nochmal kontrollieren — vollständig?",
      "Notfallplan für die Geburt: Wie komme ich in die Klinik? Wer passt auf Geschwister auf?",
      "Wochenbettbetreuung durch Hebamme organisieren",
    ],
    tips: [
      "Vierfüßlerstand und Kreisen der Hüften hilft beim Drehen des Babys",
      "Auf Wehen-App hinweisen (misst Abstand und Dauer)",
      "Letzte Ruhepause genießen — schlafen, wenn möglich",
      "Wärme auf dem Bauch entspannt und beruhigt das Baby",
    ],
    forParents: "Der Nestbautrieb ist real — und du hast wahrscheinlich schon alles dreimal umgeräumt. Das Warten ist oft das Schwerste. Es ist okay, ungeduldig zu sein. Gleichzeitig: Das Baby kommt dann, wenn es bereit ist.",
    nextWeekPreview: "Ab SSW 37 ist dein Baby offiziell geburtsreif. Jetzt kann es jederzeit losgehen.",
  },
  {
    sswFrom: 37,
    sswTo: 40,
    ageLabel: "SSW 37–40",
    trimester: 3,
    babySize: "Wassermelone",
    babyWeightApprox: "ca. 3.200–3.500 g",
    babyDev: [
      "Dein Baby ist offiziell geburtsreif",
      "Lunge voll entwickelt — eigenständige Atmung nach Geburt möglich",
      "Alle Organe sind ausgereift und funktionsfähig",
      "Käseschmiere (Vernix) schützt die Haut und schmiert den Geburtskanal",
      "Nabelschnur liefert weiter Nährstoffe und Sauerstoff bis zur Geburt",
    ],
    bodyChanges: [
      "Wehen können jederzeit beginnen",
      "Schleimpfropf kann sich lösen (blutig-schleimiger Ausfluss)",
      "Braxton-Hicks intensivieren sich — manchmal schwer von echten Wehen zu unterscheiden",
      "Bauch senkt sich wenn das Baby tief ins Becken tritt",
      "Extrem häufiger Harndrang",
    ],
    isNormal: [
      "Unregelmäßige Übungswehen",
      "Schleimiger oder blutiger Ausfluss (Zeichnen)",
      "Starke Ungeduld und Erschöpfung",
      "Stimmungsschwankungen und Nervosität",
    ],
    watchOut: [
      "Regelmäßige Wehen (alle 5 Min, 1 Min lang, seit 1 Stunde) → Kreißsaal",
      "Blasensprung — sofort in die Klinik, auch ohne Wehen",
      "Starke Blutungen — Notruf 112",
      "Keine Kindsbewegungen mehr über mehrere Stunden",
    ],
    todos: [
      "Kreißsaalrundgang gemacht?",
      "Klinikbeutel griffbereit (Flur, nicht Keller)",
      "Geburtszentrum-Nummer im Handy",
      "Wehen-App bereit",
      "Begleitperson informiert und erreichbar",
    ],
    tips: [
      "Viel Gehen kann die Geburt anregen",
      "Wärme (Bad, Wärmflasche) entspannt den Beckenboden",
      "Dates essen soll Wehen fördern — zumindest schaden sie nicht",
      "Ruhe und Geduld: das Baby kommt dann, wenn es bereit ist",
    ],
    forParents: "Gleich ist es so weit. Egal wie die Geburt verläuft — ob wie geplant oder ganz anders — du wirst es schaffen. Vertraue deinem Körper, deiner Hebamme und dir selbst. Du trägst dieses Baby schon seit Monaten — die stärkste Arbeit liegt hinter dir.",
    nextWeekPreview: "Dein Baby kommt bald. Die nächste große Aufgabe beginnt.",
  },
];

export function getPregnancyBlock(ssw: number): PregnancyBlock {
  return (
    PREGNANCY_BLOCKS.find((b) => ssw >= b.sswFrom && ssw <= b.sswTo) ??
    (ssw < 4 ? PREGNANCY_BLOCKS[0] : PREGNANCY_BLOCKS[PREGNANCY_BLOCKS.length - 1])
  );
}

export const PREGNANCY_MILESTONES: { ssw: number; label: string; emoji: string }[] = [
  { ssw: 4,  label: "Einnistung abgeschlossen",          emoji: "🌱" },
  { ssw: 5,  label: "Herzschlag beginnt",                emoji: "💓" },
  { ssw: 8,  label: "Alle Organe angelegt",              emoji: "🧬" },
  { ssw: 10, label: "Aus Embryo wird Fötus",             emoji: "🌿" },
  { ssw: 12, label: "1. Trimester geschafft",            emoji: "🎉" },
  { ssw: 16, label: "Kindsbewegungen möglich",           emoji: "🦋" },
  { ssw: 20, label: "Halbzeit!",                         emoji: "⭐" },
  { ssw: 20, label: "Geschlecht erkennbar",              emoji: "👶" },
  { ssw: 24, label: "Überlebensfähigkeit beginnt",       emoji: "💪" },
  { ssw: 28, label: "3. Trimester beginnt",              emoji: "🏁" },
  { ssw: 32, label: "Lunge fast ausgereift",             emoji: "🫁" },
  { ssw: 36, label: "Geburtsposition",                   emoji: "🔄" },
  { ssw: 37, label: "Geburtsreife erreicht",             emoji: "✅" },
  { ssw: 40, label: "Errechneter Geburtstermin",         emoji: "🍼" },
];
